### ISSUE TITLE
LICENSE.txt is created a the root of the project

### ISSUE THREAD

**Issue by ljani** [nortal/Utilities.Csv#3]
The current NuGet package [creates a `LICENSE.txt`](https://github.com/nortal/Utilities.Csv/blob/be54398c5d5fe060c6ab39d2edd74e92ccfdf112/Csv/_tools/NugetPackaging/Nortal.Utilities.Csv.nuspec#L21) in the root of my own project. I'd prefer if you didn't relicense my project when I add this library through NuGet.

**Comment by ImrePyhvel** [comment]
The original intent was to help users remember to include the licence as required by Apache licence distribution requirement 4b:
"You must give any other recipients of the Work or Derivative Works a copy of this License; "

But I agree (an have stumbled on this myself) that adding the license file with that plain name "License" is undesirable and may conflict with your own work & licensing. Alternatives would be to either:
* NOT add this file at all and let users remember themselvest to look up and include the license.
* still copy the license to project but with a better name or location.

The first option is not wrong but requires extra steps from users. The latter may be useful but can also be a nuisance if the proposed location/name does not fit your plans for license inclusion..

I lean a bit toward preferring the "do nothing" option for next release.

**Comment by ljani** [comment]
Why not this:


Element | Description
------------ | -------------
requireLicenseAcceptance | A Boolean value that specifies whether the client needs to ensure that the package license (described by licenseUrl) is accepted before the package is installed.

**Comment by ImrePyhvel** [comment]
The decision is to NOT add this file at all and let users remember themselves to look up and include the license. Will be available soon in v0.10.0 first prerelease version.
